# Generated by Django 5.1.6 on 2025-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('C', 'Cliente'), ('P', 'Profissional')], default='C', max_length=1),
        ),
    ]
