# Generated by Django 5.1.7 on 2025-06-18 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Aceito'), ('R', 'Recusado'), ('E', 'Em análise')], default='E', max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo', models.DateField()),
                ('dataInicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('E', 'Em andamento')], default='E', max_length=1)),
                ('dataInicio', models.DateField()),
                ('dataConclusao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='C', max_length=1)),
                ('categoria', models.CharField(choices=[('ES', 'Escoamento'), ('PI', 'Pintura'), ('RE', 'Reforma'), ('CO', 'Construção'), ('VI', 'Vidracaria'), ('MA', 'Marcenaria'), ('FR', 'Freteiro'), ('MO', 'Montagem'), ('EL', 'Elétrica')], default='RE', max_length=2)),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
