# Generated by Django 5.1.6 on 2025-05-22 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_endereco_alter_user_type_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TicketServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='C', max_length=1)),
                ('categoria', models.CharField(choices=[('ES', 'Escoamento'), ('PI', 'Pintura'), ('RE', 'Reforma'), ('CO', 'Construcao'), ('VI', 'Vidracaria'), ('MA', 'Marcenaria'), ('FR', 'Freteiro'), ('MO', 'Montagem'), ('EL', 'Eletrica')], default='RE', max_length=2)),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.endereco')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
